name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy-back:
    name: Build and Deploy Back-end
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: fuze365/curriculum-back
        dockerfile: curriculum-back/Dockerfile
        tags: latest

  build-and-deploy-front:
    name: Build and Deploy Front-end
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: fuze365/curriculum-front
        dockerfile: curriculum-front/Dockerfile
        tags: latest
